spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

datasource:
  master:
      driver-class-name: "oracle.jdbc.driver.OracleDriver"
      url: "jdbc:oracle:thin:@220.117.243.55:1521:WMS"
      user-name: "WMS_USER"
      password: "WMS_USER"
      initial-size: 10
      max-active: 10
      max-idle: 10
      min-idle: 10
      max-wait : 3000

#    jpa:
#        database: H2
#    datasource:
#        url: jdbc:h2:mem:testdb
#        username: sa
#        password: 
#        driverClassName: org.h2.Driver

